### ISSUE TITLE
when running the app in release mode  it always gets me disconnected

### ISSUE THREAD

**Issue by m4hmoud-atef** [mabdelatief/tap_joy_plugin#2]
when running the app in release mode i get disconnected in the state of the sdk, i have tried the example app, cloned the repo but it didn't work, please help
BTW it's working fine in the debug mode, only gets an exception when showing the Offerwall, not connecting

**Comment by mabdelatief** [comment]
it might be a problem with tapjoy account, please re-check your account configurations and let me know.
also, let me know if you get a specific exception or error

**Comment by m4hmoud-atef** [comment]
it was a problem with progaurd , thx for creating the pckg btw

**Comment by mabdelatief** [comment]
sure, anytime, i've closed this issue .

**Comment by mabdelatief** [comment]
> it was a problem with progaurd , thx for creating the pckg btw
can you please contact me ? 
m.abdelatief@gmail.com
