### ISSUE TITLE
Not woking in IOS.

### ISSUE THREAD

**Issue by varunkamanibosc** [mabdelatief/tap_joy_plugin#4]
Hi, i am getting the following error:

Unhandled Exception: MissingPluginException(No implementation found for method connectTapJoy on channel tap_joy_plugin)    MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)

**Comment by SR-Wendell** [comment]
I have the same error , but I solved with command "Flutter Clean " and after use command "Flutter build", with me this solution solved  mistake.
